### ISSUE TITLE
Final Capstone Project

### ISSUE THREAD

**Issue by zkr024** [NeckerFree/CarsAPI#23]
The main topic of the app will be a car site, where the user is able to create a list of the cars of his/her selection.

- Set a back-end app:

Create API, routes, and methods to interact with the API

- Set a front-end app:

Follow the design patterns provided to build an app that feeds from the API previously created.

Team:
@NeckerFree 
@amrendrakind 
@zkr024 

Project Repo Link : https://github.com/NeckerFree/CarsAPI

kanban project - https://github.com/NeckerFree/CarsAPI/projects/1

**Screenshot of the current state of their Kanban board**

![Screenshot from 2022-08-19 02-56-44](https://user-images.githubusercontent.com/78268827/185498705-63671348-99b3-4077-b95d-9a0672020092.png)
![Screenshot from 2022-08-19 02-57-01](https://user-images.githubusercontent.com/78268827/185498720-43badb5a-e079-43c6-897b-14dca7a53076.png)
![Screenshot from 2022-08-19 02-57-06](https://user-images.githubusercontent.com/78268827/185498762-830180b5-9444-4d9f-a7ef-cc548a75405b.png)

**Comment by vichuge** [comment]
Hi dear student, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![cat_massage](https://user-images.githubusercontent.com/20563252/121368971-16d2dc00-c901-11eb-9123-7f578bf64118.gif)

## Invalid Code Review Request

You have submitted a project, that doesn't have the next:
- A link to the GitHub project
- a screenshot of the current state of their Kanban board 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by amrendrakind** [comment]
@vichuge Thank you for your feedback. We implemented your recommendations.

**Comment by vichuge** [comment]
Hi dear student, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
